# Generated by Django 3.1.4 on 2021-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(error_messages={'unique': 'User_id already exists'}, primary_key=True, serialize=False, unique=True),
        ),
    ]
