# Generated by Django 3.2.8 on 2021-10-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('O', 'Outflow'), ('I', 'Inflow')], max_length=7)),
                ('category', models.CharField(max_length=20)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
            ],
        ),
    ]
