# Generated by Django 3.1.4 on 2021-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(error_messages={'unique': 'Account_ID already exists'}, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.BigAutoField(error_messages={'unique': 'Reference already exists'}, primary_key=True, serialize=False, unique=True),
        ),
    ]
